name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean test

  semantic-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2 

      - name: Run semantic-release
        if: github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
